FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json tsconfig.json ./
RUN npm install
COPY src ./src
RUN npm run build

FROM node:20-alpine AS runtime
WORKDIR /app
COPY package.json ./
COPY --from=builder /app/dist ./dist
RUN npm install --production
EXPOSE 4000
CMD ["node", "dist/index.js"]
